"""Configuration management for latom simulations."""

import json
from dataclasses import asdict, dataclass
from pathlib import Path


@dataclass
class SimulationConfig:
    """Configuration for a Helium TDSE simulation.

    All values have defaults matching the original hardcoded parameters
    in TDSE.cc. Units are atomic units unless noted.
    """

    # Grid parameters
    grid_nx: int = 1500
    grid_ny: int = 1500
    grid_dx: float = 0.2
    grid_dy: float = 0.2

    # Imaginary time propagation (ground state)
    imag_dt: float = 0.25
    imag_steps: int = 100

    # Real time propagation (laser dynamics)
    real_dt: float = 0.1
    real_steps: int = 2000

    # Output control
    obs_every: int = 1
    wf_every: int = 200

    # Physics parameters
    ionization_box: int = 50
    init_type: int = 3
    coulomb_eps: float = 1.0
    absorb_ampl: float = 50.0

    # Laser parameters (velocity gauge)
    laser_freq: float = 1.556
    laser_alpha: float = 0.1
    laser_cycles: float = 40.0

    # Excited states
    n_excited: int = 0
    load_ground: int = 0

    # Output file names
    output_dir: str = "res"
    wf_file: str = "wf_laser.dat"
    obser_file: str = "obser_laser.dat"
    obser_imag_file: str = "obserimag_laser.dat"
    reading_file: str = "wf_ground.dat"

    def write_ini(self, path):
        """Write configuration as INI file for the C++ solver.

        Args:
            path: Path to write the config file.
        """
        path = Path(path)
        lines = []
        lines.append("# latom simulation configuration")
        lines.append("# Generated by latom Python GUI\n")
        for key, value in asdict(self).items():
            lines.append(f"{key} = {value}")
        path.write_text("\n".join(lines) + "\n")

    def save_json(self, path):
        """Save configuration as JSON for GUI persistence.

        Args:
            path: Path to write the JSON file.
        """
        path = Path(path)
        path.write_text(json.dumps(asdict(self), indent=2))

    @classmethod
    def load_json(cls, path):
        """Load configuration from a JSON file.

        Args:
            path: Path to the JSON config file.

        Returns:
            SimulationConfig instance.
        """
        path = Path(path)
        data = json.loads(path.read_text())
        return cls(**data)
